import hvacImg from "@/assets/consumer/hvac.png";
import { HvacEquipment } from "./types";

export const HVAC_EQUIPMENT: HvacEquipment[] = [
  // Heat Pumps
  {
    id: "daikin-altherma-3-h-ht-16kw",
    category: "heatPumps",
    brand: "DAIKIN",
    model: "Altherma 3 H HT 16kW",
    imageUrl: hvacImg,
    outputSpec: "16 kW heat output",
    technology: "ASHP high-temp",
    additionalSpec: "COP 3.1 at -7°C",
    efficiencyRating: "A+++",
    warrantyYears: 5,
    rating: 4,
    price: 8400,
  },
  {
    id: "mitsubishi-ecodan-cahv-r450-16kw",
    category: "heatPumps",
    brand: "MITSUBISHI",
    model: "Ecodan CAHV-R450 16kW",
    imageUrl: hvacImg,
    outputSpec: "16 kW heat output",
    technology: "R32 refrigerant",
    additionalSpec: "COP 4.0 at 7°C",
    efficiencyRating: "A+++",
    warrantyYears: 5,
    rating: 4,
    price: 9200,
  },
  {
    id: "viessmann-vitocal-200-a-18kw",
    category: "heatPumps",
    brand: "VIESSMANN",
    model: "Vitocal 200-A 18kW",
    imageUrl: hvacImg,
    outputSpec: "18 kW heat output",
    technology: "ASHP monobloc",
    additionalSpec: "COP 4.3 at 2°C",
    efficiencyRating: "A+++",
    warrantyYears: 5,
    rating: 4,
    price: 7800,
  },

  // Air Conditioners
  {
    id: "carrier-infinity-24vna7",
    category: "airConditioners",
    brand: "CARRIER",
    model: "Infinity 24VNA7 3-ton",
    imageUrl: hvacImg,
    outputSpec: "3 ton / 36,000 BTU",
    technology: "Variable speed",
    additionalSpec: "SEER2 22.0",
    efficiencyRating: "A+++",
    warrantyYears: 10,
    rating: 4,
    price: 6200,
  },
  {
    id: "lennox-xc25-4ton",
    category: "airConditioners",
    brand: "LENNOX",
    model: "XC25 4-ton",
    imageUrl: hvacImg,
    outputSpec: "4 ton / 48,000 BTU",
    technology: "Precise Comfort",
    additionalSpec: "SEER2 26.2",
    efficiencyRating: "A+++",
    warrantyYears: 10,
    rating: 4,
    price: 7500,
  },

  // Air Handling Units
  {
    id: "trane-ahu-modular-5ton",
    category: "airHandlingUnits",
    brand: "TRANE",
    model: "Modular AHU 5-ton",
    imageUrl: hvacImg,
    outputSpec: "5 ton / 2,000 CFM",
    technology: "Variable air volume",
    additionalSpec: "MERV 13 filtration",
    efficiencyRating: "A++",
    warrantyYears: 7,
    rating: 4,
    price: 9800,
  },
  {
    id: "york-ahu-compact-3ton",
    category: "airHandlingUnits",
    brand: "YORK",
    model: "Compact AHU 3-ton",
    imageUrl: hvacImg,
    outputSpec: "3 ton / 1,200 CFM",
    technology: "ECM blower motor",
    additionalSpec: "Low sound operation",
    efficiencyRating: "A++",
    warrantyYears: 5,
    rating: 4,
    price: 6100,
  },

  // Ventilation Systems
  {
    id: "zehnder-comfoair-q450",
    category: "ventilationSystems",
    brand: "ZEHNDER",
    model: "ComfoAir Q450 ERV",
    imageUrl: hvacImg,
    outputSpec: "450 m³/hr airflow",
    technology: "Energy recovery ventilator",
    additionalSpec: "90% heat recovery",
    efficiencyRating: "A+++",
    warrantyYears: 5,
    rating: 4,
    price: 4200,
  },
  {
    id: "panasonic-intellibalance-200",
    category: "ventilationSystems",
    brand: "PANASONIC",
    model: "Intelli-Balance 200",
    imageUrl: hvacImg,
    outputSpec: "200 CFM balanced ERV",
    technology: "Energy recovery ventilator",
    additionalSpec: "Whole-home fresh air",
    efficiencyRating: "A++",
    warrantyYears: 5,
    rating: 4,
    price: 1650,
  },

  // Thermostats & Controls
  {
    id: "ecobee-smart-premium",
    category: "thermostatsControls",
    brand: "ECOBEE",
    model: "Smart Thermostat Premium",
    imageUrl: hvacImg,
    outputSpec: "Whole-home control",
    technology: "WiFi / Sensors",
    additionalSpec: "Room occupancy sensing",
    efficiencyRating: "N/A",
    warrantyYears: 3,
    rating: 4,
    price: 250,
  },
  {
    id: "honeywell-t10-pro",
    category: "thermostatsControls",
    brand: "HONEYWELL",
    model: "T10 Pro Smart Thermostat",
    imageUrl: hvacImg,
    outputSpec: "Zoned control ready",
    technology: "WiFi / Geofencing",
    additionalSpec: "Multi-zone compatible",
    efficiencyRating: "N/A",
    warrantyYears: 3,
    rating: 4,
    price: 220,
  },

  // HVAC Accessories
  {
    id: "aprilaire-humidifier-600",
    category: "accessories",
    brand: "APRILAIRE",
    model: "Model 600 Humidifier",
    imageUrl: hvacImg,
    outputSpec: "Whole-house humidification",
    technology: "Fan-powered",
    additionalSpec: "Covers up to 4,000 sq ft",
    efficiencyRating: "N/A",
    warrantyYears: 5,
    rating: 4,
    price: 380,
  },
  {
    id: "merv13-filter-set",
    category: "accessories",
    brand: "FILTRETE",
    model: "MERV 13 Filter Set (4-pack)",
    imageUrl: hvacImg,
    outputSpec: "High-efficiency filtration",
    technology: "Electrostatic pleated",
    additionalSpec: "Captures allergens & smoke",
    efficiencyRating: "N/A",
    warrantyYears: 1,
    rating: 4,
    price: 65,
  },
  {
    id: "duct-sealing-kit",
    category: "accessories",
    brand: "GENERIC",
    model: "Duct Sealing & Insulation Kit",
    imageUrl: hvacImg,
    outputSpec: "Reduces duct losses",
    technology: "Mastic sealant + wrap",
    additionalSpec: "Improves system efficiency",
    efficiencyRating: "N/A",
    warrantyYears: 10,
    rating: 4,
    price: 145,
  },
];
