import { HVACEquipment } from "./TechnicalSpecifications";

export const monthlyLoadProfile = [
  { month: "Jan", cooling: 820, heating: 1390, baseline: 310 },
  { month: "Feb", cooling: 750, heating: 1270, baseline: 305 },
  { month: "Mar", cooling: 935, heating: 950, baseline: 310 },
  { month: "Apr", cooling: 1170, heating: 540, baseline: 305 },
  { month: "May", cooling: 1540, heating: 170, baseline: 305 },
  { month: "Jun", cooling: 1960, heating: 0, baseline: 305 },
];

export const hvacEquipmentList: HVACEquipment[] = [
  {
    id: "daikin-vrv-a",
    name: "Daikin VRV-A Series",
    category: "VRF System",
    rating: "A+++",
    capacityTon: 12,
    cop: 4.2,
    estimatedCost: 28400,
    systemConfiguration: {
      systemType: "Variable Refrigerant Flow (VRF)",
      coolingCapacity: "42 kW (12 Ton)",
      heatingCapacity: "48 kW",
      refrigerant: "R-32 (Low GWP — 675)",
      controlSystem: "BMS-Integrated Smart Control",
      zoneCount: "5 independent floor zones",
    },
    financialAnalysis: {
      equipmentCost: 28400,
      installationCost: 8200,
      totalInvestment: 36600,
      annualSavings: 2840,
      paybackPeriodYears: 12.9,
      netSavings20Year: 20200,
    },
    environmentalImpact: {
      co2ReductionTonsPerYear: 8.2,
      energySavingsPercent: 22,
      refrigerantGwp: 675,
    },
    monthlyLoadProfile,
  },
  {
    id: "mitsubishi-city-multi",
    name: "Mitsubishi City Multi",
    category: "VRF System",
    rating: "A+++",
    capacityTon: 10,
    cop: 4.5,
    estimatedCost: 24100,
    systemConfiguration: {
      systemType: "Variable Refrigerant Flow (VRF)",
      coolingCapacity: "35 kW (10 Ton)",
      heatingCapacity: "40 kW",
      refrigerant: "R-32 (Low GWP — 675)",
      controlSystem: "BMS-Integrated Smart Control",
      zoneCount: "4 independent floor zones",
    },
    financialAnalysis: {
      equipmentCost: 24100,
      installationCost: 7400,
      totalInvestment: 31500,
      annualSavings: 3010,
      paybackPeriodYears: 10.5,
      netSavings20Year: 26700,
    },
    environmentalImpact: {
      co2ReductionTonsPerYear: 8.9,
      energySavingsPercent: 25,
      refrigerantGwp: 675,
    },
    monthlyLoadProfile,
  },
  {
    id: "carrier-aquasnap-30rb",
    name: "Carrier AquaSnap 30RB",
    category: "Air-Cooled Chiller",
    rating: "A++",
    capacityTon: 15,
    cop: 3.8,
    estimatedCost: 34200,
    systemConfiguration: {
      systemType: "Air-Cooled Chiller",
      coolingCapacity: "53 kW (15 Ton)",
      heatingCapacity: "N/A",
      refrigerant: "R-454B (Low GWP — 466)",
      controlSystem: "Standalone Digital Control",
      zoneCount: "1 central plant",
    },
    financialAnalysis: {
      equipmentCost: 34200,
      installationCost: 9800,
      totalInvestment: 44000,
      annualSavings: 2210,
      paybackPeriodYears: 19.9,
      netSavings20Year: 12200,
    },
    environmentalImpact: {
      co2ReductionTonsPerYear: 6.4,
      energySavingsPercent: 16,
      refrigerantGwp: 466,
    },
    monthlyLoadProfile,
  },
  {
    id: "trane-intellipak",
    name: "Trane Intellipak",
    category: "Packaged RTU",
    rating: "A+",
    capacityTon: 12,
    cop: 3.5,
    estimatedCost: 19800,
    systemConfiguration: {
      systemType: "Packaged Rooftop Unit (RTU)",
      coolingCapacity: "42 kW (12 Ton)",
      heatingCapacity: "45 kW (gas heat)",
      refrigerant: "R-410A (GWP — 2088)",
      controlSystem: "Programmable Thermostat",
      zoneCount: "1 zone",
    },
    financialAnalysis: {
      equipmentCost: 19800,
      installationCost: 6100,
      totalInvestment: 25900,
      annualSavings: 1480,
      paybackPeriodYears: 17.5,
      netSavings20Year: 9500,
    },
    environmentalImpact: {
      co2ReductionTonsPerYear: 4.1,
      energySavingsPercent: 11,
      refrigerantGwp: 2088,
    },
    monthlyLoadProfile,
  },
];
