import windTurbine from "@/assets/consumer/wind.png";
import { WindEquipment } from "./types";

export const WIND_EQUIPMENT: WindEquipment[] = [
  // Wind Turbines
  {
    id: "bergey-excel-10r-10kw",
    category: "windTurbines",
    brand: "BERGEY WIND",
    model: "Excel 10-R 10kW",
    imageUrl: windTurbine,
    outputSpec: "10 kW rated power",
    technology: "HAWT 3-blade",
    additionalSpec: "Cp 0.38 max",
    efficiencyRating: "Class S",
    warrantyYears: 10,
    rating: 4,
    price: 22500,
  },
  {
    id: "enair-70l-5kw",
    category: "windTurbines",
    brand: "ENAIR",
    model: "ENAIR 70L 5kW",
    imageUrl: windTurbine,
    outputSpec: "5 kW rated power",
    technology: "HAWT 5-blade",
    additionalSpec: "Cp 0.40 max",
    efficiencyRating: "Class S",
    warrantyYears: 5,
    rating: 4,
    price: 14800,
  },
  {
    id: "northern-power-nps-60-24-60kw",
    category: "windTurbines",
    brand: "NORTHERN POWER",
    model: "NPS 60-24 60kW",
    imageUrl: windTurbine,
    outputSpec: "60 kW rated power",
    technology: "Direct drive",
    additionalSpec: "Cp 0.44 max",
    efficiencyRating: "Class II",
    warrantyYears: 20,
    rating: 4,
    price: 95000,
  },

  // Inverters
  {
    id: "sma-windy-boy-11kw",
    category: "inverters",
    brand: "SMA",
    model: "Windy Boy 11kW",
    imageUrl: windTurbine,
    outputSpec: "11 kW output",
    technology: "Grid-tie inverter",
    additionalSpec: "97.0% efficiency",
    efficiencyRating: "A+++",
    warrantyYears: 10,
    rating: 4,
    price: 3200,
  },
  {
    id: "outback-fx-8kw",
    category: "inverters",
    brand: "OUTBACK POWER",
    model: "FX 8kW Inverter",
    imageUrl: windTurbine,
    outputSpec: "8 kW output",
    technology: "Hybrid inverter",
    additionalSpec: "95.5% efficiency",
    efficiencyRating: "A++",
    warrantyYears: 5,
    rating: 4,
    price: 2400,
  },

  // Controllers
  {
    id: "morningstar-tristar-60",
    category: "controllers",
    brand: "MORNINGSTAR",
    model: "TriStar TS-60",
    imageUrl: windTurbine,
    outputSpec: "60A charge rating",
    technology: "PWM controller",
    additionalSpec: "Diversion load capable",
    efficiencyRating: "A++",
    warrantyYears: 5,
    rating: 4,
    price: 385,
  },
  {
    id: "midnite-classic-150",
    category: "controllers",
    brand: "MIDNITE SOLAR",
    model: "Classic 150",
    imageUrl: windTurbine,
    outputSpec: "150V max input",
    technology: "MPPT controller",
    additionalSpec: "Whizbang Jr. compatible",
    efficiencyRating: "A+++",
    warrantyYears: 5,
    rating: 4,
    price: 620,
  },

  // Monitoring Systems
  {
    id: "bergey-turbine-monitor",
    category: "monitoringSystems",
    brand: "BERGEY WIND",
    model: "Turbine Monitor Pro",
    imageUrl: windTurbine,
    outputSpec: "Real-time monitoring",
    technology: "WiFi / Cellular",
    additionalSpec: "Wind speed logging",
    efficiencyRating: "N/A",
    warrantyYears: 3,
    rating: 4,
    price: 425,
  },
  {
    id: "midnite-whizbang-jr",
    category: "monitoringSystems",
    brand: "MIDNITE SOLAR",
    model: "Whizbang Jr.",
    imageUrl: windTurbine,
    outputSpec: "Amp-hour metering",
    technology: "RPM sensor",
    additionalSpec: "Overspeed protection",
    efficiencyRating: "N/A",
    warrantyYears: 3,
    rating: 4,
    price: 165,
  },

  // Wind Accessories
  {
    id: "guy-wire-kit-heavy-duty",
    category: "accessories",
    brand: "GENERIC",
    model: "Heavy-Duty Guy Wire Kit",
    imageUrl: windTurbine,
    outputSpec: "Tower support system",
    technology: "Galvanized steel cable",
    additionalSpec: "Rated to 60m towers",
    efficiencyRating: "N/A",
    warrantyYears: 10,
    rating: 4,
    price: 340,
  },
  {
    id: "tower-mounting-bracket",
    category: "accessories",
    brand: "BERGEY WIND",
    model: "Tilt-Up Tower Bracket",
    imageUrl: windTurbine,
    outputSpec: "Universal mount",
    technology: "Hinged base plate",
    additionalSpec: "Simplifies maintenance",
    efficiencyRating: "N/A",
    warrantyYears: 15,
    rating: 4,
    price: 580,
  },
  {
    id: "lightning-arrestor-kit",
    category: "accessories",
    brand: "MIDNITE SOLAR",
    model: "Lightning Arrestor Kit",
    imageUrl: windTurbine,
    outputSpec: "Surge protection",
    technology: "MNSPD device",
    additionalSpec: "NEC compliant",
    efficiencyRating: "N/A",
    warrantyYears: 5,
    rating: 4,
    price: 95,
  },
];
