import biomassImg from "@/assets/consumer/biomass.png";
import { BiomassEquipment } from "./types";

export const BIOMASS_EQUIPMENT: BiomassEquipment[] = [
  // Pellet Boilers
  {
    id: "froling-p4-pellet-30kw",
    category: "pelletBoilers",
    brand: "FRÖLING",
    model: "P4 Pellet 30kW",
    imageUrl: biomassImg,
    outputSpec: "30 kW thermal",
    technology: "Auto-feed hopper",
    additionalSpec: "94.2% efficiency",
    efficiencyRating: "A+++",
    warrantyYears: 5,
    rating: 4,
    price: 12800,
  },
  {
    id: "okofen-pellematic-smart-28",
    category: "pelletBoilers",
    brand: "ÖKOFEN",
    model: "Pellematic Smart 28",
    imageUrl: biomassImg,
    outputSpec: "28 kW thermal",
    technology: "Condensing",
    additionalSpec: "95.0% efficiency",
    efficiencyRating: "A+++",
    warrantyYears: 7,
    rating: 4,
    price: 15200,
  },
  {
    id: "windhager-biowin2-touch-30",
    category: "pelletBoilers",
    brand: "WINDHAGER",
    model: "BioWIN2 Touch 30",
    imageUrl: biomassImg,
    outputSpec: "30 kW thermal",
    technology: "Lambda controlled",
    additionalSpec: "93.8% efficiency",
    efficiencyRating: "A++",
    warrantyYears: 5,
    rating: 4,
    price: 13500,
  },

  // Biogas Generator Kits
  {
    id: "homebiogas-2-0",
    category: "biogasKits",
    brand: "HOMEBIOGAS",
    model: "HomeBiogas 2.0",
    imageUrl: biomassImg,
    outputSpec: "2 hrs cooking gas/day",
    technology: "Anaerobic digester",
    additionalSpec: "Handles 6L food waste/day",
    efficiencyRating: "A+",
    warrantyYears: 3,
    rating: 4,
    price: 1250,
  },
  {
    id: "puxin-10m3-digester",
    category: "biogasKits",
    brand: "PUXIN",
    model: "10m³ Biogas Digester",
    imageUrl: biomassImg,
    outputSpec: "10 m³ capacity",
    technology: "Fixed dome digester",
    additionalSpec: "Livestock waste compatible",
    efficiencyRating: "A",
    warrantyYears: 5,
    rating: 4,
    price: 3400,
  },

  // Biomass Conversion Systems
  {
    id: "ankur-gasifier-25kw",
    category: "conversionSystems",
    brand: "ANKUR SCIENTIFIC",
    model: "Downdraft Gasifier 25kW",
    imageUrl: biomassImg,
    outputSpec: "25 kW electrical",
    technology: "Downdraft gasification",
    additionalSpec: "Biomass to syngas",
    efficiencyRating: "A++",
    warrantyYears: 5,
    rating: 4,
    price: 18900,
  },
  {
    id: "biomax-15-chp",
    category: "conversionSystems",
    brand: "BIOMAX",
    model: "BioMax 15 CHP",
    imageUrl: biomassImg,
    outputSpec: "15 kW combined heat & power",
    technology: "Gasification CHP",
    additionalSpec: "Wood chip compatible",
    efficiencyRating: "A+++",
    warrantyYears: 7,
    rating: 4,
    price: 24500,
  },

  // Feedstock Equipment
  {
    id: "wood-chipper-shredder-pro",
    category: "feedstockEquipment",
    brand: "TIMBERWOLF",
    model: "TW 150PH Chipper Shredder",
    imageUrl: biomassImg,
    outputSpec: "6 in max chip capacity",
    technology: "PTO-driven",
    additionalSpec: "Diesel powered",
    efficiencyRating: "N/A",
    warrantyYears: 3,
    rating: 4,
    price: 6200,
  },
  {
    id: "pellet-mill-flat-die",
    category: "feedstockEquipment",
    brand: "KAHL",
    model: "Flat Die Pellet Mill",
    imageUrl: biomassImg,
    outputSpec: "200 kg/hr output",
    technology: "Flat die pelletizer",
    additionalSpec: "6-8mm pellet diameter",
    efficiencyRating: "A++",
    warrantyYears: 5,
    rating: 4,
    price: 8900,
  },
  {
    id: "biomass-dryer-rotary",
    category: "feedstockEquipment",
    brand: "SUNCUE",
    model: "Rotary Drum Dryer",
    imageUrl: biomassImg,
    outputSpec: "500 kg/hr drying capacity",
    technology: "Rotary drum",
    additionalSpec: "Reduces moisture to 10-12%",
    efficiencyRating: "A+",
    warrantyYears: 3,
    rating: 4,
    price: 11400,
  },

  // Biomass Accessories
  {
    id: "pellet-storage-silo-3t",
    category: "accessories",
    brand: "FRÖLING",
    model: "3-Ton Storage Silo",
    imageUrl: biomassImg,
    outputSpec: "3 tons capacity",
    technology: "Flexible fabric silo",
    additionalSpec: "Auto-feed compatible",
    efficiencyRating: "N/A",
    warrantyYears: 10,
    rating: 4,
    price: 1850,
  },
  {
    id: "ash-removal-vacuum",
    category: "accessories",
    brand: "ÖKOFEN",
    model: "Automatic Ash Vacuum",
    imageUrl: biomassImg,
    outputSpec: "Auto ash removal",
    technology: "Pneumatic extraction",
    additionalSpec: "Reduces maintenance",
    efficiencyRating: "N/A",
    warrantyYears: 3,
    rating: 4,
    price: 640,
  },
  {
    id: "flue-gas-monitor",
    category: "accessories",
    brand: "WINDHAGER",
    model: "Flue Gas Analyzer",
    imageUrl: biomassImg,
    outputSpec: "Real-time emissions data",
    technology: "O2 / CO sensor",
    additionalSpec: "Combustion optimization",
    efficiencyRating: "N/A",
    warrantyYears: 2,
    rating: 4,
    price: 480,
  },
];
