import solar from "@/assets/consumer/solar.png";
import { SolarEquipment } from "./types";

export const SOLAR_EQUIPMENT: SolarEquipment[] = [
  // Solar PV Modules
  {
    id: "jinko-tiger-neo-n-type-400w",
    category: "pvModules",
    brand: "JINKO SOLAR",
    model: "Tiger Neo N-Type 400W",
    imageUrl: solar,
    outputSpec: "400W peak output",
    technology: "Monocrystalline PERC",
    additionalSpec: "21.3% efficiency",
    efficiencyRating: "A+++",
    warrantyYears: 25,
    rating: 4,
    price: 185,
  },
  {
    id: "longi-hi-mo-6-explorer-410w",
    category: "pvModules",
    brand: "LONGI SOLAR",
    model: "Hi-MO 6 Explorer 410W",
    imageUrl: solar,
    outputSpec: "410W peak output",
    technology: "HJT Technology",
    additionalSpec: "22.0% efficiency",
    efficiencyRating: "A+++",
    warrantyYears: 30,
    rating: 4,
    price: 210,
  },
  {
    id: "canadian-bihiku7-cs7n-420w",
    category: "pvModules",
    brand: "CANADIAN SOLAR",
    model: "BiHiKu7 CS7N 420W",
    imageUrl: solar,
    outputSpec: "420W peak output",
    technology: "Bifacial N-Type",
    additionalSpec: "21.6% efficiency",
    efficiencyRating: "A++",
    warrantyYears: 25,
    rating: 4,
    price: 195,
  },
  {
    id: "trina-vertex-s-neg9-415w",
    category: "pvModules",
    brand: "TRINA SOLAR",
    model: "Vertex S+ NEG9 415W",
    imageUrl: solar,
    outputSpec: "415W peak output",
    technology: "N-Type TOPCon",
    additionalSpec: "21.8% efficiency",
    efficiencyRating: "A+++",
    warrantyYears: 25,
    rating: 4,
    price: 178,
  },

  // Inverters
  {
    id: "sma-sunny-boy-7-7kw",
    category: "inverters",
    brand: "SMA",
    model: "Sunny Boy 7.7kW",
    imageUrl: solar,
    outputSpec: "7.7 kW output",
    technology: "String inverter",
    additionalSpec: "97.6% efficiency",
    efficiencyRating: "A+++",
    warrantyYears: 10,
    rating: 4,
    price: 1450,
  },
  {
    id: "enphase-iq8-microinverter",
    category: "inverters",
    brand: "ENPHASE",
    model: "IQ8+ Microinverter",
    imageUrl: solar,
    outputSpec: "290W per panel",
    technology: "Microinverter",
    additionalSpec: "97.5% efficiency",
    efficiencyRating: "A+++",
    warrantyYears: 25,
    rating: 4,
    price: 189,
  },
  {
    id: "solaredge-se7600h",
    category: "inverters",
    brand: "SOLAREDGE",
    model: "SE7600H HD-Wave",
    imageUrl: solar,
    outputSpec: "7.6 kW output",
    technology: "DC optimized",
    additionalSpec: "99.0% efficiency",
    efficiencyRating: "A+++",
    warrantyYears: 12,
    rating: 4,
    price: 1680,
  },

  // Mounting Systems
  {
    id: "ironridge-xr100-rail",
    category: "mountingSystems",
    brand: "IRONRIDGE",
    model: "XR100 Rail System",
    imageUrl: solar,
    outputSpec: "168 in rail length",
    technology: "Aluminum rail",
    additionalSpec: "Wind rated 180 mph",
    efficiencyRating: "N/A",
    warrantyYears: 20,
    rating: 4,
    price: 320,
  },
  {
    id: "unirac-solarmount-hd",
    category: "mountingSystems",
    brand: "UNIRAC",
    model: "SolarMount HD",
    imageUrl: solar,
    outputSpec: "Universal rail",
    technology: "Roof-mount",
    additionalSpec: "Fire Class A rated",
    efficiencyRating: "N/A",
    warrantyYears: 25,
    rating: 4,
    price: 285,
  },

  // Monitoring Devices
  {
    id: "enphase-envoy-s-metered",
    category: "monitoringDevices",
    brand: "ENPHASE",
    model: "Envoy-S Metered",
    imageUrl: solar,
    outputSpec: "Real-time monitoring",
    technology: "WiFi / Cellular",
    additionalSpec: "Per-panel tracking",
    efficiencyRating: "N/A",
    warrantyYears: 5,
    rating: 4,
    price: 349,
  },
  {
    id: "solaredge-monitoring-portal",
    category: "monitoringDevices",
    brand: "SOLAREDGE",
    model: "Monitoring Gateway",
    imageUrl: solar,
    outputSpec: "Cloud dashboard",
    technology: "Ethernet / WiFi",
    additionalSpec: "Fault detection alerts",
    efficiencyRating: "N/A",
    warrantyYears: 5,
    rating: 4,
    price: 279,
  },

  // Solar Accessories
  {
    id: "mc4-connector-kit",
    category: "accessories",
    brand: "STAUBLI",
    model: "MC4 Connector Kit",
    imageUrl: solar,
    outputSpec: "1000V rated",
    technology: "Weatherproof connector",
    additionalSpec: "IP68 rated",
    efficiencyRating: "N/A",
    warrantyYears: 10,
    rating: 4,
    price: 45,
  },
  {
    id: "solar-cable-10awg",
    category: "accessories",
    brand: "GENERIC",
    model: "10AWG PV Wire (100ft)",
    imageUrl: solar,
    outputSpec: "600V rated",
    technology: "UV-resistant cable",
    additionalSpec: "Copper conductor",
    efficiencyRating: "N/A",
    warrantyYears: 25,
    rating: 4,
    price: 78,
  },
  {
    id: "rapid-shutdown-device",
    category: "accessories",
    brand: "TIGO",
    model: "TS4-A-O Rapid Shutdown",
    imageUrl: solar,
    outputSpec: "Module-level shutdown",
    technology: "RSD compliant",
    additionalSpec: "NEC 690.12 compliant",
    efficiencyRating: "N/A",
    warrantyYears: 10,
    rating: 4,
    price: 55,
  },
];
