import evImg from "@/assets/consumer/ev.png";
import { EvEquipment } from "./types";

export const EV_EQUIPMENT: EvEquipment[] = [
  // EV Chargers
  {
    id: "abb-terra-ac-w11-g5-r-0",
    category: "evChargers",
    brand: "ABB",
    model: "Terra AC W11-G5-R-0",
    imageUrl: evImg,
    outputSpec: "11 kW / 3-phase",
    technology: "RFID + App ctrl",
    additionalSpec: "OCPP 2.0.1",
    efficiencyRating: "A+++",
    warrantyYears: 3,
    rating: 4,
    price: 1900,
  },
  {
    id: "wallbox-pulsar-plus-22kw",
    category: "evChargers",
    brand: "WALLBOX",
    model: "Pulsar Plus 22 kW",
    imageUrl: evImg,
    outputSpec: "22 kW / 1-3 ph",
    technology: "Bluetooth LE",
    additionalSpec: "Power sharing",
    efficiencyRating: "A+++",
    warrantyYears: 3,
    rating: 4,
    price: 1400,
  },
  {
    id: "chargepoint-ct4011-level-2",
    category: "evChargers",
    brand: "CHARGEPOINT",
    model: "CT4011 Level 2",
    imageUrl: evImg,
    outputSpec: "7.7 kW / 1-phase",
    technology: "Cloud managed",
    additionalSpec: "Fleet ready",
    efficiencyRating: "A++",
    warrantyYears: 3,
    rating: 4,
    price: 2200,
  },

  // DC Fast Chargers
  {
    id: "abb-terra-184-dc-fast",
    category: "dcFastChargers",
    brand: "ABB",
    model: "Terra 184 CC",
    imageUrl: evImg,
    outputSpec: "184 kW DC output",
    technology: "CCS + CHAdeMO",
    additionalSpec: "Simultaneous dual charging",
    efficiencyRating: "A+++",
    warrantyYears: 3,
    rating: 4,
    price: 68000,
  },
  {
    id: "tritium-rtm75-dc-fast",
    category: "dcFastChargers",
    brand: "TRITIUM",
    model: "RTM75 DC Fast Charger",
    imageUrl: evImg,
    outputSpec: "75 kW DC output",
    technology: "Liquid cooled",
    additionalSpec: "Compact footprint",
    efficiencyRating: "A++",
    warrantyYears: 3,
    rating: 4,
    price: 42000,
  },

  // Charging Stations
  {
    id: "flo-x5-dual-port",
    category: "chargingStations",
    brand: "FLO",
    model: "FLO X5 Dual Port",
    imageUrl: evImg,
    outputSpec: "2 × 7.2 kW ports",
    technology: "Networked pedestal",
    additionalSpec: "Weatherproof enclosure",
    efficiencyRating: "A++",
    warrantyYears: 5,
    rating: 4,
    price: 5200,
  },
  {
    id: "chargepoint-cpf50-pedestal",
    category: "chargingStations",
    brand: "CHARGEPOINT",
    model: "CPF50 Pedestal Station",
    imageUrl: evImg,
    outputSpec: "1 × 30A / 7.2 kW",
    technology: "Commercial pedestal",
    additionalSpec: "ADA compliant",
    efficiencyRating: "A++",
    warrantyYears: 5,
    rating: 4,
    price: 3800,
  },

  // Charging Management
  {
    id: "chargepoint-fleet-mgmt-software",
    category: "chargingManagement",
    brand: "CHARGEPOINT",
    model: "Fleet Management Software",
    imageUrl: evImg,
    outputSpec: "Cloud-based platform",
    technology: "Load balancing",
    additionalSpec: "Real-time usage analytics",
    efficiencyRating: "N/A",
    warrantyYears: 1,
    rating: 4,
    price: 1200,
  },
  {
    id: "enel-x-juicenet-enterprise",
    category: "chargingManagement",
    brand: "ENEL X",
    model: "JuiceNet Enterprise",
    imageUrl: evImg,
    outputSpec: "Multi-site management",
    technology: "Dynamic load management",
    additionalSpec: "Demand response ready",
    efficiencyRating: "N/A",
    warrantyYears: 1,
    rating: 4,
    price: 1450,
  },

  // EV Accessories
  {
    id: "type2-extension-cable-5m",
    category: "evAccessories",
    brand: "GENERIC",
    model: "Type 2 Extension Cable 5m",
    imageUrl: evImg,
    outputSpec: "32A rated",
    technology: "IP55 rated cable",
    additionalSpec: "Weatherproof connectors",
    efficiencyRating: "N/A",
    warrantyYears: 2,
    rating: 4,
    price: 180,
  },
  {
    id: "wall-mount-cable-holder",
    category: "evAccessories",
    brand: "WALLBOX",
    model: "Cable Holder & Organizer",
    imageUrl: evImg,
    outputSpec: "Wall-mounted",
    technology: "Weatherproof bracket",
    additionalSpec: "Prevents cable damage",
    efficiencyRating: "N/A",
    warrantyYears: 3,
    rating: 4,
    price: 45,
  },
  {
    id: "rfid-card-pack-10",
    category: "evAccessories",
    brand: "CHARGEPOINT",
    model: "RFID Access Card (10-pack)",
    imageUrl: evImg,
    outputSpec: "10 cards",
    technology: "RFID access control",
    additionalSpec: "Fleet driver access",
    efficiencyRating: "N/A",
    warrantyYears: 1,
    rating: 4,
    price: 95,
  },

  // Electric Vehicles
  {
    id: "ford-e-transit-cargo",
    category: "electricVehicles",
    brand: "FORD",
    model: "E-Transit Cargo Van",
    imageUrl: evImg,
    outputSpec: "126 mile range",
    technology: "68 kWh battery",
    additionalSpec: "Fleet configuration ready",
    efficiencyRating: "A++",
    warrantyYears: 8,
    rating: 4,
    price: 48500,
  },
  {
    id: "rivian-edv-700",
    category: "electricVehicles",
    brand: "RIVIAN",
    model: "EDV 700",
    imageUrl: evImg,
    outputSpec: "150 mile range",
    technology: "Commercial delivery van",
    additionalSpec: "Purpose-built for fleets",
    efficiencyRating: "A+++",
    warrantyYears: 8,
    rating: 4,
    price: 72000,
  },
];
