import batteryImg from "@/assets/consumer/evInfo.png";
import { BatteryEquipment } from "./types";

export const BATTERY_EQUIPMENT: BatteryEquipment[] = [
  // Battery Systems
  {
    id: "tesla-powerwall-3",
    category: "batterySystems",
    brand: "TESLA",
    model: "Powerwall 3 (13.5 kWh)",
    imageUrl: batteryImg,
    outputSpec: "13.5 kWh capacity",
    technology: "LFP chemistry",
    additionalSpec: "97.5% round-trip",
    efficiencyRating: "A+++",
    warrantyYears: 10,
    rating: 4,
    price: 11500,
  },
  {
    id: "byd-battery-box-premium-hvm22",
    category: "batterySystems",
    brand: "BYD",
    model: "Battery-Box Premium HVM 22",
    imageUrl: batteryImg,
    outputSpec: "22 kWh capacity",
    technology: "Modular LFP",
    additionalSpec: "96.0% round-trip",
    efficiencyRating: "A+++",
    warrantyYears: 10,
    rating: 4,
    price: 14800,
  },
  {
    id: "sonnen-batterie-eco-10",
    category: "batterySystems",
    brand: "SONNEN",
    model: "SonnenBatterie eco 10",
    imageUrl: batteryImg,
    outputSpec: "10 kWh capacity",
    technology: "All-in-one",
    additionalSpec: "90.0% round-trip",
    efficiencyRating: "A++",
    warrantyYears: 10,
    rating: 4,
    price: 12200,
  },
  {
    id: "lg-resu-prime-16",
    category: "batterySystems",
    brand: "LG",
    model: "RESU Prime 16H",
    imageUrl: batteryImg,
    outputSpec: "16 kWh capacity",
    technology: "Lithium-ion NMC",
    additionalSpec: "94.5% round-trip",
    efficiencyRating: "A++",
    warrantyYears: 10,
    rating: 4,
    price: 13100,
  },
  {
    id: "enphase-iq-battery-10",
    category: "batterySystems",
    brand: "ENPHASE",
    model: "IQ Battery 10T",
    imageUrl: batteryImg,
    outputSpec: "10.5 kWh capacity",
    technology: "LFP, AC-coupled",
    additionalSpec: "89.0% round-trip",
    efficiencyRating: "A+",
    warrantyYears: 15,
    rating: 5,
    price: 10900,
  },

  // Inverters
  {
    id: "solaredge-energy-hub-10kw",
    category: "inverters",
    brand: "SOLAREDGE",
    model: "Energy Hub Inverter 10kW",
    imageUrl: batteryImg,
    outputSpec: "10 kW output",
    technology: "Hybrid inverter",
    additionalSpec: "97.6% efficiency",
    efficiencyRating: "A+++",
    warrantyYears: 12,
    rating: 5,
    price: 3200,
  },
  {
    id: "sma-sunny-boy-storage-6kw",
    category: "inverters",
    brand: "SMA",
    model: "Sunny Boy Storage 6.0",
    imageUrl: batteryImg,
    outputSpec: "6 kW output",
    technology: "Battery inverter",
    additionalSpec: "96.5% efficiency",
    efficiencyRating: "A++",
    warrantyYears: 10,
    rating: 4,
    price: 2650,
  },
  {
    id: "victron-multiplus-ii-5kw",
    category: "inverters",
    brand: "VICTRON",
    model: "MultiPlus-II 5kW",
    imageUrl: batteryImg,
    outputSpec: "5 kW output",
    technology: "Inverter/charger",
    additionalSpec: "96.0% efficiency",
    efficiencyRating: "A++",
    warrantyYears: 5,
    rating: 4,
    price: 2100,
  },

  // Charge Controllers
  {
    id: "midnite-classic-150",
    category: "chargeControllers",
    brand: "MIDNITE SOLAR",
    model: "Classic 150 MPPT",
    imageUrl: batteryImg,
    outputSpec: "150V, 96A max",
    technology: "MPPT",
    additionalSpec: "99.0% tracking",
    efficiencyRating: "A+++",
    warrantyYears: 5,
    rating: 4,
    price: 780,
  },
  {
    id: "victron-smartsolar-150-100",
    category: "chargeControllers",
    brand: "VICTRON",
    model: "SmartSolar MPPT 150/100",
    imageUrl: batteryImg,
    outputSpec: "150V, 100A max",
    technology: "MPPT",
    additionalSpec: "98.5% tracking",
    efficiencyRating: "A++",
    warrantyYears: 5,
    rating: 5,
    price: 690,
  },

  // Monitoring Systems
  {
    id: "sense-home-energy-monitor",
    category: "monitoringSystems",
    brand: "SENSE",
    model: "Home Energy Monitor",
    imageUrl: batteryImg,
    outputSpec: "Whole-home CT clamps",
    technology: "Real-time ML monitoring",
    additionalSpec: "1s sampling rate",
    efficiencyRating: "N/A",
    warrantyYears: 1,
    rating: 4,
    price: 360,
  },
  {
    id: "tesla-gateway-2",
    category: "monitoringSystems",
    brand: "TESLA",
    model: "Backup Gateway 2",
    imageUrl: batteryImg,
    outputSpec: "200A gateway",
    technology: "Cloud monitoring app",
    additionalSpec: "Automatic load shedding",
    efficiencyRating: "N/A",
    warrantyYears: 10,
    rating: 4,
    price: 1450,
  },

  // Battery Accessories
  {
    id: "battery-rapid-shutdown-kit",
    category: "accessories",
    brand: "SOLAREDGE",
    model: "Rapid Shutdown Kit",
    imageUrl: batteryImg,
    outputSpec: "NEC 2020 compliant",
    technology: "Module-level shutdown",
    additionalSpec: "Fire-safety compliant",
    efficiencyRating: "N/A",
    warrantyYears: 5,
    rating: 4,
    price: 210,
  },
  {
    id: "battery-cabinet-enclosure",
    category: "accessories",
    brand: "GENERIC",
    model: "Outdoor Battery Enclosure",
    imageUrl: batteryImg,
    outputSpec: "NEMA 3R rated",
    technology: "Weatherproof cabinet",
    additionalSpec: "Fits up to 2 units",
    efficiencyRating: "N/A",
    warrantyYears: 3,
    rating: 3,
    price: 480,
  },
  {
    id: "battery-monitoring-shunt",
    category: "accessories",
    brand: "VICTRON",
    model: "SmartShunt 500A/50mV",
    imageUrl: batteryImg,
    outputSpec: "500A rated",
    technology: "Bluetooth battery monitor",
    additionalSpec: "State-of-charge tracking",
    efficiencyRating: "N/A",
    warrantyYears: 5,
    rating: 4,
    price: 140,
  },
];
